version: "3.8"

services:
  # User Service
  user-service:
    build:
      context: ./user-service
      dockerfile: Dockerfile
      target: runtime
    ports:
      - "8000:8000"
    networks:
      - app-network

  # Product Service
  product-service:
    build:
      context: ./product-service
      dockerfile: Dockerfile
      target: runtime
    ports:
      - "8001:8001"
    networks:
      - app-network
    volumes:
      - shared-data:/app/shared
      - logs-data:/app/logs

volumes:
  shared-data:
    driver: local
  logs-data:
    driver: local

networks:
  app-network:
    driver: bridge
